/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details take a look at the Writing Custom Plugins chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/custom_plugins.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("java-gradle-plugin")
  id("org.jetbrains.kotlin.jvm") version "1.5.31"
  id("maven-publish")
  id("com.gradle.plugin-publish") version "0.16.0"
}

version = "v0.0.1"
group = "io.github.fish895623"

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  // Align versions of all Kotlin components
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

  // Use the Kotlin JDK 8 standard library.
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
}

pluginBundle {
  website = "https://github.com/fish895623/alert-messages.git/"
  vcsUrl = "https://github.com/fish895623/alert-messages.git/"
  tags = listOf("tags", "for", "your", "plugins")
}

gradlePlugin {
  plugins {
    create("gradleTestPlugin") {
      id = "io.github.fish895623.greeting"
      displayName = "testingPlugin"
      description = "for testing"
      implementationClass = "io.github.fish895623.AlertMessagesPlugin"
    }
  }
}

gradlePlugin.testSourceSets(sourceSets["functionalTest"])

tasks.named<Task>("check") {
  // Include functionalTest as part of the check lifecycle
  dependsOn(testing.suites.named("functionalTest"))
}
publishing {
  repositories {
    maven {
      name = "Github"
      url = uri("https://github.com/fish895623/alert-messages/")
      credentials {
        username = "fish895623"
        password = ""
      }
    }
  }
}