/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.fish895623

import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'com.github.fish895623.greeting' plugin.
 */
class AlertMessagesPluginFunctionalTest {
  @get:Rule
  val tempFolder = TemporaryFolder()

  private fun getProjectDir() = tempFolder.root
  private fun getBuildFile() = getProjectDir().resolve("build.gradle")
  private fun getSettingsFile() = getProjectDir().resolve("settings.gradle")

  @Test
  fun `can run task`() {
    // Setup the test build
    getSettingsFile().writeText("")
    getBuildFile().writeText(
      """
plugins {
    id('com.github.fish895623.greeting')
}
"""
    )

    // Run the build
    val runner = GradleRunner.create()
    runner.forwardOutput()
    runner.withPluginClasspath()
    runner.withArguments("greeting")
    runner.withProjectDir(getProjectDir())
    val result = runner.build()

    // Verify the result
    assertTrue(result.output.contains("Hello from plugin 'com.github.fish895623.greeting'"))
  }
}
