/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.fish895623

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class AlertMessagesPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'com.github.fish895623.greeting'")
            }
        }
    }
}
