/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.fish895623

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.github.fish895623.greeting' plugin.
 */
class AlertMessagesPluginTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.github.fish895623.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
